version: "2.1"
orbs:
  aws-cli: circleci/aws-cli@3.1.3

executors:
  packer:
    docker:
      - image: "hashicorp/packer:light"

jobs:
  packer-build:
    executor: packer
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            apk add curl jq
      - run:
          name: Packer init
          command: |
            packer init packer/
      - run:
          name: Packer build
          command: |
            packer build -force --var-file=packer/vars.packer.hcl packer/ami.pkr.hcl
      - store_artifacts:
          path: manifest.json
          destination: manifest.json
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: .
          # Must be relative path from root
          paths:
            - manifest.json

  rolling-update:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/workspace
      - run:
          name: cat
          command: |
            cat /tmp/workspace/manifest.json
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION
      - run:
          name: Rolling update
          command: |
            # Read AMI_ID from manifest.json 
            NEW_AMI_ID=$(jq -r '.builds[0].artifact_id|split(":")[1]' /tmp/workspace/manifest.json) \
            bash ./.circleci/scripts/rolling_update.sh

  setup-eks-node:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION
      - run:
          name: Install eksctl
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version

      - run:
          name: Setup
          command: |
            bash ./.circleci/scripts/scale_up_eks_node.sh

workflows:
  deploy-staging:
    jobs:
      - packer-build:
          context:
            - aws
          filters:
            tags:
              only: /^staging$/
            branches:
              ignore: /.*/
      - rolling-update:
          context:
            - aws
          requires:
            - packer-build
          filters:
            tags:
              only: /^staging$/
            branches:
              ignore: /.*/

  wait-for-eks:
    jobs:
      - setup-eks-node:
          context:
            - aws
