version: "2.1"
orbs:
  aws-cli: circleci/aws-cli@3.1.3

executors:
  packer:
    docker:
      - image: "hashicorp/packer:light"

jobs:
  packer-build:
    executor: packer
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            apk add curl
      - run:
          name: Packer init
          command: |
            packer init packer/
      - run:
          name: Build image with packer
          command: |
            packer build --var-file=packer/vars.packer.hcl packer/ami.pkr.hcl
      - store_artifacts:
          path: manifest.json
          destination: manifest.json

  rolling-update:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_REGION
          profile-name: default
      - run:
          name: Rolling update
          command: |
            bash ./.circleci/scripts/rolling_update.sh
workflows:
  deploy-staging:
    jobs:
      - packer-build:
          context:
            - aws
          filters:
            tags:
              only: /^staging$/
            branches:
              ignore: /.*/
      - rolling-update:
          context:
            - aws
          requires:
            - packer-build
          filters:
            tags:
              only: /^staging$/
            branches:
              ignore: /.*/
